# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting_name', models.CharField(max_length=128)),
                ('painting_code', models.CharField(max_length=64, unique=True)),
                ('painting_size', models.CharField(max_length=32)),
                ('painting_cost', models.PositiveIntegerField()),
                ('painting_discounted_cost', models.PositiveIntegerField()),
                ('painting_image_big', models.TextField()),
                ('painting_image_small', models.TextField()),
                ('artist_name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaintingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64)),
                ('category_code', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
