# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0002_painting_paintingcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='belongs_to_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paints.PaintingCategory'),
        ),
    ]
