# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0004_otpsave_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='otpsave',
            name='mobile',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='otpsave',
            name='saved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
