# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0010_painting_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='is_favourite',
        ),
        migrations.AddField(
            model_name='user',
            name='is_favourite',
            field=models.ManyToManyField(to='paints.Painting'),
        ),
    ]
