# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0011_auto_20180706_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_favourite',
        ),
    ]
