# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0012_remove_user_is_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('order_number', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=512, null=True)),
                ('order_items', models.TextField()),
                ('status', models.CharField(choices=[('Not Yet Shipped', 'Not Yet Shipped'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Not Yet Shipped', max_length=120)),
                ('shipping_total', models.CharField(max_length=126)),
                ('total', models.CharField(max_length=126)),
                ('placed_at', models.DateTimeField()),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('expected_delivery', models.DateTimeField()),
                ('email_sent', models.BooleanField(default=False)),
                ('payment_accepted', models.BooleanField(default=False)),
                ('refund_made', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paints.User')),
            ],
        ),
    ]
