# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0013_order_placeorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeorder',
            old_name='expected_delivery',
            new_name='expected_at',
        ),
        migrations.RemoveField(
            model_name='placeorder',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='placeorder',
            name='payment_accepted',
        ),
        migrations.RemoveField(
            model_name='placeorder',
            name='refund_made',
        ),
        migrations.RemoveField(
            model_name='placeorder',
            name='shipping_total',
        ),
        migrations.RemoveField(
            model_name='placeorder',
            name='total',
        ),
        migrations.RemoveField(
            model_name='placeorder',
            name='user',
        ),
        migrations.AddField(
            model_name='placeorder',
            name='order_total',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='payment_mode',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='rzp_payment_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='rzp_refund_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='user_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='user_email',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='user_mobile',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='user_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='placeorder',
            name='status',
            field=models.CharField(default='received', max_length=120),
        ),
    ]
