# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0015_auto_20180708_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allorder',
            name='user_address',
        ),
        migrations.AddField(
            model_name='allorder',
            name='logged_in_email',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='allorder',
            name='logged_in_mobile',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='allorder',
            name='logged_in_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
